###
GET http://localhost:5291/

###
GET http://localhost:5291/produto/listar

###
GET http://localhost:5291/produto/buscar/Bicicleta

###
POST http://localhost:5291/produto/cadastrar
content-type: application/json

{
    "nome": "TV"
}

###
DELETE http://localhost:5291/produto/deletar
content-type: application/json

{
    "nome": "TV"
}