[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///db/control_wallet.db'
TITLE = 'Control Wallet'
SECRET_KEY = '138c0c90-0f35-429b-9f2d-84c7d95b7973'
EXTENSIONS = [
  "app.extensions.database",
  "app.extensions.commands",
  "app.blueprints.views",
]
