version: '4'

networks:
  default:
    external: false
  traefik-public:
    external: true

services:

  traefik:
    container_name: traefik
    hostname: traefik
    image: "traefik:v2.4"
    restart: unless-stopped
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "80:80"
      - "443:443"
#      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_letsencrypt:/letsencrypt"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dominios@qosit.com.br"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.lbswarm=true"
#      - "traefik.http.routers.traefik.rule=Host(`traefik.brothersinf.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
#      - "traefik.http.routers.traefik.middlewares=auth"
#      - "traefik.http.routers.traefik.service=api@internal"
#      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
#      - "traefik.http.middlewares.auth.basicauth.users=admin:{SHA}AVJqQdtl86yijIflRNi/KAYIwD8="
#      - "traefik.http.routers.traefik.entrypoints=websecure"
#      - "traefik.http.routers.traefik.tls.certresolver=le"
    networks:
      - traefik-public

volumes:
  traefik_letsencrypt:
