[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///control_wallet.db'
TITLE = 'Control Wallet'
SECRET_KEY = '138c0c90-0f35-429b-9f2d-84c7d95b7973'
EXTENSIONS = [
  "app.extensions.database",
  "app.extensions.commands",
  "app.blueprints.views",
]
MAIL_SERVER = 'smtp.emailemnuvem.com.br'
MAIL_PORT = '465'
MAIL_USE_TLS = 'False'
MAIL_USE_SSL = 'True'
MAIL_USERNAME = 'suporte@qosit.com.br'
MAIL_PASSWORD = 'Qqosit-0215#'
MAIL_DEFAULT_SENDER = 'suporte@qosit.com.br'